Query TMDB API
yamovie/server pull request #1
Opened 2019-03-12 15:45 UTC by glenflorendo

Resolves yamovie/client#94

2019-04-03 17:58 UTC, afterafx reviewed
Looks good to me, code is clean and naming conventions are on point

2019-04-04 20:27 UTC, samsaksfithian requested changes

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +  else return allGenres;
This should return the ```res.json```, which also makes it so you don't actually need the if-else, and satisfies that the arrow function always returns something:

```suggestion
if (res) { 
  return res.json(allGenres); 
}
return allGenres;
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> + * @return  genres
Include return type in comment for readability, and also the parameter types. 
e.g.:
```suggestion
/**
 * Serves an array of movie genres
 * @param {??} res the response // this should probably be more descriptive than I have it here
 * @return {Promise} genres
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +module.exports.readAll = async (req, res) => {
This function never actually uses ```req```, so is it necessary to even have it as a parameter?

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +  res.json(foundGenre);
Should this return the res.json explicitly and check to see if it actually found one, like the function above?
```suggestion
  return res.json(foundGenre);
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +  Genre.findOne({ 'external_ids.tmdb_id': key }).exec();
Make this one line with no break after the arrow. 
```suggestion
const readOneByKey = key => Genre.findOne({ 'external_ids.tmdb_id': key }).exec();
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +const { configs } = require('../utils');
You never actually use this in the code, so you should remove the import.

```suggestion

```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> + * @return  array of movies
Add params to the JDoc comment, since you have a request and response. Also the type of the return, for readability.

```suggestion
/**
 * Returns all data from every movie.
 * @param {??} req
 * @param {??} res
 * @return {Promise} array of movies
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +  res.json(allMovies);
Shouldn't this explicitly return the ```res.json```, just like genreController? Also potentially check to make sure there is a response to return?

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +module.exports.readOne = async (req, res) => {
The JDoc comment for this function makes no sense to me. It says the param is id, but it actually has two params, ```req``` and ```res```, but no ```id```. Also, idk what ```promise, movie``` means for the return. If promise is the type and movie is the description, you should put 'promise' in the type specifier format, i.e. ```{Promise}``` (which you should also do for the parameter types)

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +  res.json(foundMovie);
Same as above, shouldn't this be an explicit return?
```suggestion
  return res.json(foundMovie);
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +  res.json(foundMovies);
Same thing as above, explicit return?
```suggestion
  return res.json(foundMovies);
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> + */
```js
/**
 * INTERNAL USE ONLY --
 * Create new Movie document
 * @param {??} movie
 * @returns {Promise} the new movie object
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/movieController.js
> +module.exports.create = movie => Movie.create(movie);
Same thing as genreController, it'd be cleaner if each function is just a constant and then there's a single export at the end.

```suggestion
const create = movie => Movie.create(movie);

module.exports = {
  readAll,
  readOne,
  readByGenre,
  create,
};
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/errorHandler.js
> +  return res.status(err.status || 500).json({
This function could be an implicit return since that's all it does.

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/errorHandler.js
> +module.exports = (err, req, res, next) => {
```req``` and ```next``` are never actually used, so do you need them here at all?

Also, JDoc comment, especially since you have so many params that the user needs to know how to enter.
```js
/**
 * Does some stuff
 * @param {??} err
 * @param {??} req
 * @param {??} res
 * @param {??} next
 * @returns {???} ???
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/errorHandler.js
> +      message: error.message || 'Oops! Something went wrong',
`error` doesn't exist here, I think you meant to use your `err` parameter.

```suggestion
      message: err.message || 'Oops! Something went wrong',
```

2019-04-04 20:27 UTC, samsaksfithian commented on .eslintrc
> +{
I think I've added some new rules to the front end one since creation, so you should go grab and copy that to make sure they're the same.

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +module.exports = (req, res, next) => {
This is a very confusing function that defines and contains other functions. Structured this way, it looks and behaves kinda like a class, so I think it would be more readable if it just was actually turned into a class.

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +const getPrefix = req => {
Hoist both this function and the next one to the top, above the exports, so they're defined before being used.

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +const getLoggerByStatusCode = status => {
Again, hoist this to the top

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +  else return console.log.bind(console);
You don't need the else's, because the ifs return

```suggestion
if (status >= 400) return console.warn.bind(console);
return console.log.bind(console);
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +const shortId = require('shortid');
This file has a ton of console logs, mostly for good reason, so just to shut up ESLint for this file add an ignore at the top:
```suggestion
/* eslint-disable no-console */
const shortId = require('shortid');
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +  const error = error => {
```error``` is double defined, both as the constant function name and as your parameter. Rename the parameter to ```err``` or something
```suggestion
  const error = err => {
```
```js
const error = err => {
  cleanup();
  console(`${getPrefix(req)} Request pipeline error: ${err}`);
};
```

2019-04-04 20:27 UTC, samsaksfithian commented on routes/index.js
> +router.get('/', (req, res) => {
```req``` is never used, so is it necessary to have as parameter?

2019-04-04 20:27 UTC, samsaksfithian commented on server.js
> +const app = express();
Add a newline before this, just to visually separate the import section

```suggestion

const app = express();
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/index.js
> +};
Same as the controller things, group your exports for cleaner code:

```suggestion
const getGenres = async () => {
  const genreResponse = await tmdb.requestGenres();
  return genreResponse.data;
};

module.exports = {
  updateConfigurations,
  getMovies,
  getMoviesData,
  getGenres,
};
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/index.js
> +  let movieData = tmdbResponses.map(response => response.data);
You never reassign, so this should be a `const` instead of `let`

```suggestion
  const movieData = tmdbResponses.map(response => response.data);
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/index.js
> +  for await (let datum of movieData) {
ESLint is mad about something, I think because it doesn't understand `for await`, so just tell it to shut up

Also, `datum` is never reassigned, so it should be `const`, I think

```suggestion
// eslint-disable-next-line no-restricted-syntax
for await (const datum of movieData) {
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/omdb/index.js
> +
```suggestion
/**
 * Asks for some movie details?
 * @param {??} id the id of the movie, or something?
 * @returns {??} something?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/omdb/index.js
> +exports.requestMovieDetails = id => {
Why is this just `exports.req---` instead of `module.exports.req---`?

```suggestion
module.exports.requestMovieDetails = id => {
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +exports.requestConfigurations = () => {
This should be an implicit return, since that's all this function does.

```suggestion
const requestConfigurations = () => axios(requests.TMDB_CONFIG);
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> + * @return  {Object}  movie data
Add the params

```suggestion
/**
 * Requests TMDB API for movie data
 * @param {??} page
 * @return  {Object}  movie data
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +exports.requestGenres = () => {
Should be an implicit return.

```suggestion
const requestGenres = () => axios(requests.TMDB_GENRES);
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +};
Again, for cleanliness and to save yourself the annoyance of changing every line to `module.exports`, group them at the end:

```suggestion
module.exports = {
  requestConfigurations,
  requestNowPlayingMovies,
  requestDiscoverMovies,
  requestMovieDetails,
  requestGenres,
};
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +const seed = async () => {
Push this function down to the bottom so it's after the definition of the helper functions.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +  while (state.movies.hasMore) {
Try making this the ```for await``` thing (or any other async handling stuff, like maybe ```Promise.all```), because ESLint doesn't like the ```await```s inside a loop.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +    for await (let genre of seed.genres) {
`genre` is never reassigned so it should be `const`.

```suggestion
    for await (const genre of seed.genres) {
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +      await controllers.genre.create(await parser.genres(genre));
No initial `await`, becasue that's the whole point of the `for await`
```suggestion
      controllers.genre.create(await parser.genres(genre));
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +const setMovieState = (page, results, totalPages, totalResults) => {
Push this up by the top, so it's defined above where it's used.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +const controllers = require('../controllers');
Tell ESLint to shut up
```suggestion
/* eslint-disable no-restricted-syntax */
/* eslint-disable no-console */
const controllers = require('../controllers');
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +    await controllers.movie.create(await parser.movie(datum, movieConfigs));
Don't need the initial `await`
```suggestion
    controllers.movie.create(await parser.movie(datum, movieConfigs));
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +  for await (let datum of data) {
`datum` is never changed, so it should be `const`
```suggestion
  for await (const datum of data) {
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +  // let timer = await setTimeout(async () => {
Delete this stuff if it's not necessary anymore.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +    acc[query[0]] = query[1];
Array destructuring

```suggestion
    const [query0, query1] = query;
    acc[query0] = query1;
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Does some stuff, and has a very descriptive name
 * @param {??} url 
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +module.exports.qs = async url => {
```suggestion
const queryString = async url => {
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Does some stuff with the genres?
 * @param {??} id
 * @param {??} name
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +module.exports.genres = async ({ name, id }) => {
This function should just be an implicit return

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +module.exports.movie = async (data, configs) => {
This function should just be an implicit return.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Does some stuff with a movie?
 * @param {??} data
 * @param {??} configs
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +};
```suggestion
};

// =============================================================================
// =============================================================================
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieCredits = async ({ cast = [], crew = [] }) => {
Should be an implicit return.
```suggestion
const parseMovieCredits = async ({ cast = [], crew = [] }) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Parses some stuff?
 * @param {??} [genres] some genres
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieGenres = async (genres = []) => {
Implicit return

```suggestion
const parseMovieGenres = async (genres = []) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
As in other files, move your exports to the bottom and make your functions `const`s

```suggestion
module.exports = {
  queryString,
  genres,
  movie,
};
```

Also, pull all of your helper functions up to the top so they're defined first, before being used in the things actually being exported, and have them specifically labeled/delineated.
```suggestion
// =============================================================================
// =============================================================================
// Helper functions
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Parses some stuff?
 * @param {Object} credits
 * @param {Object} [credits.cast]
 * @param {Object} [credits.crew]
 * @returns {Promise} some stuff?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +        .map(async req => await req),
Pls refactor, because these `await`s in the returns of both this arrow function and the one a line up are redundant and don't make sense. I have no idea what this line is even doing.

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Does things
 * @param {Array<stuff?>} [companies] 
 * @param {??} configs 
 * @returns {Promise} some stuff
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieProductionCompanies = async (companies = [], configs) => {
Should be implicit return

```suggestion
const parseMovieProductionCompanies = async (companies = [], configs) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +      ({ name, logo_path, origin_country }) => {
Implicit return, also camel case

```suggestion
      ({ name, logoPath, originCountry }) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          origin_country,
```suggestion
          originCountry,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          }${logo_path}`,
```suggestion
          }${logoPath}`,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Parses some stuff
 * @param {Array<stuff>} [ratings] 
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieRatings = async (ratings = []) => {
Implicit return
```suggestion
const parseMovieRatings = async (ratings = []) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +    ratings: ratings.map(({ Source, Value }) => {
Implicit return
```suggestion
    ratings: ratings.map(({ Source, Value }) => ({ source: Source, value: Value })),
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Parses some pictures
 * @param {Object} images ??
 * @param {Array<??>} [images.backdrops] ??
 * @param {Array<??>} [images.posters] ??
 * @param {??} configs
 * @returns {Promise} ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieImages = async ({ backdrops = [], posters = [] }, configs) => {
Implicit return 

```suggestion
const parseMovieImages = async ({ backdrops = [], posters = [] }, configs) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +      backdrops: backdrops.map(({ aspect_ratio, file_path, height, width }) => {
Implicit return and camel case

```suggestion
      backdrops: backdrops.map(({ aspectRatio, filePath, height, width }) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          aspect_ratio,
```suggestion
          aspectRatio,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          }${file_path}`,
```suggestion
          }${filePath}`,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +      posters: posters.map(({ aspect_ratio, file_path, height, width }) => {
Implicit return and camel case
```suggestion
      posters: posters.map(({ aspectRatio, filePath, height, width }) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          aspect_ratio,
```suggestion
          aspectRatio,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +          }${file_path}`,
```suggestion
          }${filePath}`,
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +      cast: cast.map(({ character, name, order }) => {
Implicit return
```suggestion
      cast: cast.map(({ character, name, order }) => ({ character, name, order })),
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +      crew: crew.map(({ department, job, name }) => {
Implicit return

```suggestion
      crew: crew.map(({ department, job, name }) => ({ department, job, name })),
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +
```suggestion
/**
 * Parses some videos
 * @param {Array<stuff?>} [videos]
 * @param {??} configs
 * @returns {Promise} some stuff
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const parseMovieVideos = async (videos = [], configs) => {
Implicit return
```suggestion
const parseMovieVideos = async (videos = [], configs) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +    videos: videos.map(({ key, name, site, size, type }) => {
Implicit return
```suggestion
    videos: videos.map(({ key, name, site, size, type }) => ({
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/parser.js
> +const controllers = require('../controllers');
```suggestion
/* eslint-disable object-curly-newline */
const controllers = require('../controllers');
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +
JDoc Comment, pls <3 
e.g.:
```suggestion
/**
 * Serves a single movie genre
 * @param {??} req the request
 * @param {??} res the response
 * @return {Promise} genre
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +
JDoc comment, pls
```suggestion
/**
 * Serves a single particular genre?
 * @param {??} key the id key of a particular genre
 * @return {Promise} a genre?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on controllers/genreController.js
> +
Also, it's cleaner if you have one export thing at the very end, instead of for each method. That also will make each line a little shorter and cleaner, allowing the above format.

(This should probably be a few lines lower, below the create)
```suggestion
module.exports = {
  readAll,
  readOne,
  readOneByKey,
  create,
};
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +
As usual, JDoc comment pls
```suggestion
/**
 * Does some stuff
 * @param {??} req 
 * @returns {??} some stuff
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on middleware/logger.js
> +
Add JDoc comment

```suggestion
/**
 * Does some stuff
 * @param {??} status 
 * @returns {??} some stuff
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on routes/api.js
> +
JDoc comment, pls. Your ones for the other functions are good, so just like that.

```suggestion
/**
 * GET request for movies by genre?
 * @param   id  genre id
 * @return      array of movies?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on routes/api.js
> +
JDoc comment, pls. Your ones for the other functions are good, so just like that.

```suggestion
/**
 * GET request for genres
 * @param   id  genre id
 * @return      array of genres?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/index.js
> +
```suggestion
/**
 * Gets some movies, somehow based on page?
 * @param {??} page 
 * @returns {Promise} response movies data?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/index.js
> +
```suggestion
/**
 * Gets some movie data, somehow based on movie lists?
 * @param {??} movies
 * @returns {Promise} response movies data?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +
JDoc to specify the return

```suggestion
/**
 * Requests configs?
 * @return  {??}  ??
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +
```suggestion
/**
 * Requests something
 * @param {??} page
 * @return  {Object?}  movie data?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on services/tmdb/index.js
> +
```suggestion
/**
 * Requests TMDB API for something?
 * @param {??} id
 * @return  {Object?}  movie data?
 */
```

2019-04-04 20:27 UTC, samsaksfithian commented on utils/seed.js
> +
```suggestion
/**
 * Sets the movie state based on some stuff?
 * @param {??} page 
 * @param {??} results 
 * @param {??} totalPages 
 * @param {??} totalResults 
 */
```

2019-04-04 20:32 UTC, glenflorendo commented on controllers/genreController.js
> +  else return allGenres;
Previously, the seeder would call this, but since that is not longer the case, this will always ```return res.json```.

2019-04-04 20:40 UTC, glenflorendo commented on controllers/genreController.js
> +module.exports.readAll = async (req, res) => {
I think so, since Express will always pass those parameters in the same order.

2019-04-04 20:42 UTC, glenflorendo commented on controllers/genreController.js
> +  Genre.findOne({ 'external_ids.tmdb_id': key }).exec();
Prettier automatically separates the function into two lines for readability, since it's too long (maximum is 80 characters per line).

2019-04-04 21:14 UTC, glenflorendo commented on controllers/genreController.js
> +  res.json(foundGenre);
Nope.

2019-04-04 21:15 UTC, glenflorendo commented on controllers/movieController.js
> +  res.json(allMovies);
Nope.

2019-04-04 21:15 UTC, glenflorendo commented on controllers/movieController.js
> +  res.json(foundMovie);
Nope.

2019-04-04 21:15 UTC, glenflorendo commented on controllers/movieController.js
> +  res.json(foundMovies);
Nope.

2019-04-04 21:16 UTC, glenflorendo commented on routes/index.js
> +router.get('/', (req, res) => {
Yes, Express will always pass those parameters in that order.

2019-04-04 21:20 UTC, glenflorendo commented on services/index.js
> +  let movieData = tmdbResponses.map(response => response.data);
I change the elements inside the movieData array, so I want to be explicit that this object is being mutated in some way.

2019-04-04 21:21 UTC, glenflorendo commented on services/index.js
> +  for await (let datum of movieData) {
The properties inside datum are being mutated, so I want to be explicit that this object is being mutated in some way.

2019-04-04 21:41 UTC, glenflorendo commented on utils/parser.js
> +        .map(async req => await req),
1. For each genre, find its stored genre with `genre.readOneByKey`, which returns a `Promise`.
2. For each `Promise` request, get its response.
3. Resolve all `Promise`s asyncronously.
4. For each response, return it's `_id`.

2019-04-04 21:56 UTC, glenflorendo commented on utils/parser.js
> +      ({ name, logo_path, origin_country }) => {
API returns values in snake case. Moreover, I think MongoDB naming convention is for keys to be in snake case, so our model schemas also reflect that.

2019-04-04 22:15 UTC, glenflorendo commented on utils/seed.js
> +  while (state.movies.hasMore) {
For now, this will have to be, until I decide on a way to handle different pages asynchronously.

2019-04-04 23:41 UTC, glenflorendo commented
Done refactoring.
Pending documenting.

2019-04-05 16:56 UTC, samsaksfithian commented on services/tmdb/index.js
> -exports.requestCertifications = () => {
I don't think you meant to delete this

2019-04-05 17:10 UTC, samsaksfithian approved these changes
Fine for now, we can add any missing documentation and stuff later

2019-04-05 17:10 UTC, merged