F#84 rec limit
yamovie/server pull request #23
Opened 2019-05-22 18:50 UTC by samsaksfithian

Closes yamovie/client#84

2019-05-28 17:26 UTC, glenflorendo commented on configs/requests.js
> +      release_year_from: 2010,
Change this back to `2017`.

2019-05-28 17:28 UTC, glenflorendo commented on routes/user.js
> +// router.post('/watchlist', controllers.user.addMovieToWatchlist);
Let's just uncomment this for now.

2019-05-28 17:28 UTC, glenflorendo commented on routes/user.js
> +// router.get('/watchlist/:id', controllers.user.getWatchlistMovies);
Let's just uncomment this for now.

2019-05-28 17:28 UTC, glenflorendo commented on routes/user.js
> +// router.delete('/watchlist/:id', controllers.user.deleteWatchlistMovie);
Let's just uncomment this for now.

2019-05-28 17:29 UTC, glenflorendo requested changes
Please refer to the comments.

2019-05-28 18:13 UTC, samsaksfithian commented on configs/requests.js
> +      release_year_from: 2010,
Fiiiiine 😠

2019-05-29 17:56 UTC, glenflorendo approved these changes

2019-05-29 17:59 UTC, merged